### ISSUE TITLE
Better QSL & modded compatibility

### ISSUE THREAD

**Issue by Ampflower** [Modflower/data-driven-composter#2]
## Why?
Mods can add their own entries into the compost map, and currently, DDC is blind to those entries, treating all of them as if they were vanilla's. Right now, DDC only has ultra-coarse-grain control of all, vanilla, datapack, its own or none, and ultra-fine-grain control of the individual entries, letting one set `-1` to disable the entry or set it between 0% and 100%.

By implementing better control of what DDC does with modded entries, this can let server admins to have finer control of what entries to keep while letting them add or remove their own without much trouble.

## Why not recommend QSL?
This mod targets both Fabric and Quilt, and is geared towards those who only want to look at a central config to modify their composter entries, rather than make a datapack (which isn't as well documented currently due to QSL's Registry Entry Attachment API being relatively new and not as well used yet.)

## TODO:
- [ ] Capture both an *early* and *late* for compost maps of vanilla and modded without vanilla.
- [ ] Provide an option to omit either just vanilla or modded.
- [ ] Provide an option to omit specific namespaces, for as mods may inject early, or the server admin may only want to remove a specific mod's list.

**Comment by Shibva** [comment]
@Ampflower I have to thank you personally for developing this mod; thanks to It I can have compostable things that break for whatever reason in quilt work in quilt by adding them manually though this mod.

Thanks
